import type {
  DashboardStats,
  ChurnTrendPoint,
  RiskDistribution,
  RevenueData,
  ActivityEvent,
  Customer,
} from "@/types";

export const dashboardStats: DashboardStats = {
  totalCustomers: 12847,
  totalCustomersChange: 3.2,
  activeCustomers: 11293,
  activeCustomersChange: 1.8,
  churnRate: 4.2,
  churnRateChange: -0.8,
  mrr: 284500,
  mrrChange: 5.4,
  atRiskCustomers: 342,
  atRiskChange: -12,
  avgHealthScore: 73,
  avgHealthScoreChange: 2.1,
};

export const churnTrendData: ChurnTrendPoint[] = [
  { month: "Jul", churnRate: 5.8, predicted: 6.1 },
  { month: "Aug", churnRate: 5.2, predicted: 5.5 },
  { month: "Sep", churnRate: 4.9, predicted: 5.0 },
  { month: "Oct", churnRate: 5.1, predicted: 4.8 },
  { month: "Nov", churnRate: 4.6, predicted: 4.5 },
  { month: "Dec", churnRate: 4.8, predicted: 4.3 },
  { month: "Jan", churnRate: 4.5, predicted: 4.2 },
  { month: "Feb", churnRate: 4.3, predicted: 4.0 },
  { month: "Mar", churnRate: 4.1, predicted: 3.9 },
  { month: "Apr", churnRate: 4.2, predicted: 3.7 },
  { month: "May", churnRate: 0, predicted: 3.5 },
  { month: "Jun", churnRate: 0, predicted: 3.3 },
];

export const riskDistribution: RiskDistribution[] = [
  { level: "Low", count: 8942, percentage: 69.6, color: "#10b981" },
  { level: "Medium", count: 2245, percentage: 17.5, color: "#f59e0b" },
  { level: "High", count: 1318, percentage: 10.3, color: "#f97316" },
  { level: "Critical", count: 342, percentage: 2.7, color: "#ef4444" },
];

export const revenueData: RevenueData[] = [
  { month: "Jul", mrr: 245000, churnedRevenue: 14200, newRevenue: 18500 },
  { month: "Aug", mrr: 249300, churnedRevenue: 12900, newRevenue: 17100 },
  { month: "Sep", mrr: 253500, churnedRevenue: 12400, newRevenue: 16800 },
  { month: "Oct", mrr: 257900, churnedRevenue: 13100, newRevenue: 17500 },
  { month: "Nov", mrr: 262300, churnedRevenue: 12100, newRevenue: 16500 },
  { month: "Dec", mrr: 266700, churnedRevenue: 12600, newRevenue: 17000 },
  { month: "Jan", mrr: 271100, churnedRevenue: 12200, newRevenue: 16600 },
  { month: "Feb", mrr: 275500, churnedRevenue: 11800, newRevenue: 16200 },
  { month: "Mar", mrr: 279900, churnedRevenue: 11500, newRevenue: 15900 },
  { month: "Apr", mrr: 284500, churnedRevenue: 11900, newRevenue: 16500 },
];

export const recentActivity: ActivityEvent[] = [
  {
    id: "1",
    type: "churn",
    message: "Customer churned after 18 months",
    customer: "Acme Corp",
    timestamp: "2 min ago",
  },
  {
    id: "2",
    type: "warning",
    message: "Health score dropped below 40",
    customer: "TechFlow Inc",
    timestamp: "15 min ago",
  },
  {
    id: "3",
    type: "upgrade",
    message: "Upgraded from Starter to Pro",
    customer: "DataWave",
    timestamp: "1 hour ago",
  },
  {
    id: "4",
    type: "signup",
    message: "New customer onboarded",
    customer: "CloudNine Labs",
    timestamp: "2 hours ago",
  },
  {
    id: "5",
    type: "warning",
    message: "No login activity in 14 days",
    customer: "Nexus Digital",
    timestamp: "3 hours ago",
  },
  {
    id: "6",
    type: "downgrade",
    message: "Downgraded from Pro to Starter",
    customer: "ByteForge",
    timestamp: "4 hours ago",
  },
  {
    id: "7",
    type: "churn",
    message: "Customer churned after 6 months",
    customer: "PixelPerfect",
    timestamp: "5 hours ago",
  },
  {
    id: "8",
    type: "signup",
    message: "New enterprise customer onboarded",
    customer: "MegaSoft Corp",
    timestamp: "6 hours ago",
  },
];

export const topChurnRiskCustomers: Customer[] = [
  {
    id: "c1",
    name: "Sarah Johnson",
    email: "sarah@techflow.io",
    company: "TechFlow Inc",
    plan: "pro",
    mrr: 299,
    churnRisk: 0.92,
    lastActive: "14 days ago",
    signupDate: "2024-03-15",
    healthScore: 23,
    engagementTrend: "down",
  },
  {
    id: "c2",
    name: "Mike Chen",
    email: "mike@nexus.digital",
    company: "Nexus Digital",
    plan: "enterprise",
    mrr: 899,
    churnRisk: 0.87,
    lastActive: "21 days ago",
    signupDate: "2023-11-20",
    healthScore: 31,
    engagementTrend: "down",
  },
  {
    id: "c3",
    name: "Emily Rodriguez",
    email: "emily@byteforge.com",
    company: "ByteForge",
    plan: "starter",
    mrr: 49,
    churnRisk: 0.81,
    lastActive: "7 days ago",
    signupDate: "2024-08-10",
    healthScore: 38,
    engagementTrend: "down",
  },
  {
    id: "c4",
    name: "David Park",
    email: "david@quantum.io",
    company: "Quantum Systems",
    plan: "pro",
    mrr: 299,
    churnRisk: 0.76,
    lastActive: "5 days ago",
    signupDate: "2024-01-05",
    healthScore: 42,
    engagementTrend: "stable",
  },
  {
    id: "c5",
    name: "Lisa Wang",
    email: "lisa@streamline.co",
    company: "Streamline Co",
    plan: "pro",
    mrr: 299,
    churnRisk: 0.71,
    lastActive: "3 days ago",
    signupDate: "2024-06-22",
    healthScore: 45,
    engagementTrend: "down",
  },
];
